Repository gone-io/gonectl, pull requests merged in 2025-04, with the labels that each got.

#13 feat(install): implement goner component installation
  .gitignore
  .idea/dictionaries/project.xml
  generate/cmd_test.go
  go.mod
  go.sum
  install/cmd.go
  install/cmd_test.go
  install/testdata/module1/go.mod
  install/testdata/module1/go.sum
  install/testdata/module1/main.go
  main.go
  utils/constant.go
  utils/parser/code.go
  utils/parser/funcs.go
  utils/parser/loader.go
  utils/tools.go
Labels: kind/feature

#17 fix(install): error import when package dir was not equal to package name
  install/parser/funcs.go
  install/parser/loader.go
Labels: kind/bug

#18 feat(install): support short names for gone-io modules
  README.md
  README_CN.md
  create/clone.go
  create/clone_test.go
  create/list.go
  create/list_test.go
  create/testdata/.gitignore
  create/testdata/test.md
  install/cmd.go
  install/parser/loader.go
  install/testdata/module1/.gitignore
  install/testdata/module1/go.mod
  install/testdata/module1/go.sum
Labels: kind/enhancement

#24 feat: rename gonectr to gonectl
  .gitignore
  .goreleaser.yml
  .vscode/launch.json
  .vscode/settings.json
  README.md
  README_CN.md
  build/cmd.go
  create/clone.go
  create/cmd.go
  create/create_test.go
  generate/cmd.go
  generate/cmd_test.go
  go.mod
  install/cmd.go
  install/cmd_test.go
  install/parser/funcs.go
  install/parser/loader.go
  main.go
  mock/mock.go
  priest/cmd.go
  run/cmd.go
  testdata/projects/long_module/go.mod
  testdata/projects/single_with_go_generate/test/package.go
  utils/constant.go
  utils/tools.go
  version.go
Labels: kind/enhancement
